In [1]:
import numpy as np

In [101]:
grid = np.zeros((3, 3), dtype=int)
grid[1, 1] = 1
grid[0, 1] = 1
grid[0, 2] = 1
print(grid)

linha,coluna = grid.shape
dic={}
for i in range(linha):
    for j in range(coluna):
        celula = grid[i, j]

        cima = [i-1, j]
        baixo = [i+1, j]
        direita = [i, j+1]
        esquerda = [i, j-1]
        vizinhos = []
        if cima[0] >= 0 and cima[0] < linha and cima[1] >= 0 and cima[1] < coluna:
            vizinhos.append(cima)
        if baixo[0] >= 0 and baixo[0] < linha and baixo[1] >= 0 and baixo[1] < coluna:
            vizinhos.append(baixo)
        if direita[0] >= 0 and direita[0] < linha and direita[1] >= 0 and direita[1] < coluna:
            vizinhos.append(direita)
        if esquerda[0] >= 0 and esquerda[0] < linha and esquerda[1] >= 0 and esquerda[1] < coluna:
            vizinhos.append(esquerda)

        dic[(i, j)] = {
            'vizinhos':{
                'coord': vizinhos,
                'valores': [grid[v[0], v[1]] for v in vizinhos]}
            }
        print('##############')
        print(f"Célula ({i}, {j}): {vizinhos}")
        

[[0 1 1]
 [0 1 0]
 [0 0 0]]
##############
Célula (0, 0): [[1, 0], [0, 1]]
##############
Célula (0, 1): [[1, 1], [0, 2], [0, 0]]
##############
Célula (0, 2): [[1, 2], [0, 1]]
##############
Célula (1, 0): [[0, 0], [2, 0], [1, 1]]
##############
Célula (1, 1): [[0, 1], [2, 1], [1, 2], [1, 0]]
##############
Célula (1, 2): [[0, 2], [2, 2], [1, 1]]
##############
Célula (2, 0): [[1, 0], [2, 1]]
##############
Célula (2, 1): [[1, 1], [2, 2], [2, 0]]
##############
Célula (2, 2): [[1, 2], [2, 1]]


In [102]:
grid

array([[0, 1, 1],
       [0, 1, 0],
       [0, 0, 0]])

In [108]:
dic[(1,1)]

{'vizinhos': {'coord': [[0, 1], [2, 1], [1, 2], [1, 0]],
  'valores': [np.int64(1), np.int64(0), np.int64(0), np.int64(0)]}}